//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCv.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEdication
    {
        public int EdicationID { get; set; }
        public string Title { get; set; }
        public string Subitle1 { get; set; }
        public string Subitle2 { get; set; }
        public string GNO { get; set; }
        public string Date { get; set; }
    }
}
